### ISSUE TITLE
Docker: node-pre-gyp info This Node instance does not support builds for Node-API version 6

### ISSUE THREAD

**Issue by slecram** [pagermon/pagermon#587]
**Describe the bug**
I use the docker container. After starting the container I get the following errors in the log

```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-logo.sh: executing... 

[cont-init.d] 01-logo.sh: exited 0.
[cont-init.d] 10-adduser.sh: executing... 
GID fix
PID fix
usermod: no changes
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000 (node)
User gid:    1000 (node)
-------------------------------------
[cont-init.d] 10-adduser.sh: exited 0.
[cont-init.d] 11-defaults.sh: executing... 
[cont-init.d] 11-defaults.sh: exited 0.
[cont-init.d] 15-failmode.sh: executing... 
[cont-init.d] 15-failmode.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
node-pre-gyp info This Node instance does not support builds for Node-API version 6
node-pre-gyp info This Node instance does not support builds for Node-API version 6
[pmon]  2023-12-19 16:34:46  error : No database type was specified.
node-pre-gyp info This Node instance does not support builds for Node-API version 6
node-pre-gyp info This Node instance does not support builds for Node-API version 6
[pmon]  2023-12-19 16:34:47  error : No database type was specified.
node-pre-gyp info This Node instance does not support builds for Node-API version 6
node-pre-gyp info This Node instance does not support builds for Node-API version 6
[pmon]  2023-12-19 16:34:48  error : No database type was specified.
```

**Environment information:**
 - OS: Proxmox with Ubuntu 22.04.3 LTS and Portainer Community Edition 2.19.1

Stack:

```
version: "2"
services:
  pagermon:
    #build: ./server # To build localy
    image: pagermon/pagermon:latest
    container_name: pagermon_server
    environment:
      - APP_NAME=pagermon
      - PUID=1000 # Not required since node user inside docker has UID 1000
      - PGID=1000 # Not required since node user inside docker has GID 1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
    volumes:
      - /home/marcel/pagermon/config:/config
    restart: unless-stopped
```

I used the default config.json from 
https://github.com/pagermon/pagermon/blob/master/server/config/default.json

My containers console shows the following versions :
```
node -v
v12.16.2
npm -v
6.14.4
```
